In [29]:
# Q1: Create a DataFrame with the following e-commerce sales data:
# Columns: OrderID, CustomerID, Product, Category, Quantity, Price, OrderDate, Rating, Review
# Create at least 50 sample records with realistic data including dates from 2023-2024
# Display the first 10 and last 5 records using head() and tail()

import pandas as pd

records = {
  'OrderID': [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25],
  'CustomerID':[101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125],
  'products':[
    "Smartphone",
    "Laptop",
    "Headphones",
    "Smartwatch",
    "Bluetooth Speaker",
    "Power Bank",
    "USB Flash Drive",
    "Wireless Mouse",
    "Keyboard",
    "Monitor",
    "Printer",
    "Backpack",
    "Water Bottle",
    "Shoes",
    "T-Shirt",
    "Jeans",
    "Wrist Watch",
    "Sunglasses",
    "Wallet",
    "Notebook",
    "Pen",
    "Coffee Mug",
    "Desk Lamp",
    "Charger",
    "Earbuds"
],
'categories':[
    "Electronics",
    "Electronics",
    "Electronics",
    "Electronics",
    "Electronics",
    "Electronics",
    "Electronics",
    "Computer Accessories",
    "Computer Accessories",
    "Computer Accessories",
    "Office Equipment",
    "Fashion Accessories",
    "Daily Essentials",
    "Footwear",
    "Clothing",
    "Clothing",
    "Fashion Accessories",
    "Fashion Accessories",
    "Fashion Accessories",
    "Stationery",
    "Stationery",
    "Kitchenware",
    "Home Decor",
    "Electronics",
    "Electronics"
],
'quantity' : [
    10,  # Smartphone
    5,   # Laptop
    20,  # Headphones
    8,   # Smartwatch
    15,  # Bluetooth Speaker
    25,  # Power Bank
    30,  # USB Flash Drive
    40,  # Wireless Mouse
    35,  # Keyboard
    6,   # Monitor
    4,   # Printer
    18,  # Backpack
    50,  # Water Bottle
    22,  # Shoes
    45,  # T-Shirt
    28,  # Jeans
    12,  # Wrist Watch
    16,  # Sunglasses
    20,  # Wallet
    60,  # Notebook
    100, # Pen
    24,  # Coffee Mug
    14,  # Desk Lamp
    30,  # Charger
    26   # Earbuds
],
'prices':[
    15000,  # Smartphone
    55000,  # Laptop
    2500,   # Headphones
    7000,   # Smartwatch
    3000,   # Bluetooth Speaker
    1800,   # Power Bank
    800,    # USB Flash Drive
    900,    # Wireless Mouse
    1500,   # Keyboard
    12000,  # Monitor
    9000,   # Printer
    2000,   # Backpack
    500,    # Water Bottle
    3500,   # Shoes
    700,    # T-Shirt
    1800,   # Jeans
    4500,   # Wrist Watch
    2200,   # Sunglasses
    1200,   # Wallet
    150,    # Notebook
    20,     # Pen
    400,    # Coffee Mug
    1600,   # Desk Lamp
    1200,   # Charger
    2500    # Earbuds
],
'order_dates': [
    "2023-07-01",
    "2023-05-02",
    "2023-03-03",
    "2023-01-04",
    "2023-06-05",
    "2023-01-06",
    "2023-05-07",
    "2023-07-08",
    "2023-02-09",
    "2023-01-10",
    "2025-01-11",
    "2025-01-12",
    "2025-01-13",
    "2025-01-14",
    "2025-01-15",
    "2025-01-16",
    "2025-01-17",
    "2025-01-18",
    "2025-01-19",
    "2025-01-20",
    "2025-01-21",
    "2025-01-22",
    "2025-01-23",
    "2025-01-24",
    "2025-01-25"
],
'ratings': [4.5, 4.7, 4.3, 4.4, 4.2, 4.1, 4.0, 4.3, 4.2, 4.6, 4.4, 4.1, 4.0, 4.3, 4.2, 4.4, 4.5, 4.3, 4.2, 4.1, 3.9, 4.0, 4.2, 4.3, 4.4],

'reviews' : [1200, 980, 750, 620, 540, 680, 410, 890, 770, 650, 480, 520, 430, 610, 720, 690, 560, 590, 510, 450, 300, 340, 390, 580, 640]
}

df = pd.DataFrame(records)
print(df)
df.head(10)
df.tail(5)

    OrderID  CustomerID           products            categories  quantity  \
0         1         101         Smartphone           Electronics        10
1         2         102             Laptop           Electronics         5
2         3         103         Headphones           Electronics        20
3         4         104         Smartwatch           Electronics         8
4         5         105  Bluetooth Speaker           Electronics        15
5         6         106         Power Bank           Electronics        25
6         7         107    USB Flash Drive           Electronics        30
7         8         108     Wireless Mouse  Computer Accessories        40
8         9         109           Keyboard  Computer Accessories        35
9        10         110            Monitor  Computer Accessories         6
10       11         111            Printer      Office Equipment         4
11       12         112           Backpack   Fashion Accessories        18
12       13         113       Water Bottle      Daily Essentials        50
13       14         114              Shoes              Footwear        22
14       15         115            T-Shirt              Clothing        45
15       16         116              Jeans              Clothing        28
16       17         117        Wrist Watch   Fashion Accessories        12
17       18         118         Sunglasses   Fashion Accessories        16
18       19         119             Wallet   Fashion Accessories        20
19       20         120           Notebook            Stationery        60
20       21         121                Pen            Stationery       100
21       22         122         Coffee Mug           Kitchenware        24
22       23         123          Desk Lamp            Home Decor        14
23       24         124            Charger           Electronics        30
24       25         125            Earbuds           Electronics        26

    prices order_dates  ratings  reviews
0    15000  2023-07-01      4.5     1200
1    55000  2023-05-02      4.7      980
2     2500  2023-03-03      4.3      750
3     7000  2023-01-04      4.4      620
4     3000  2023-06-05      4.2      540
5     1800  2023-01-06      4.1      680
6      800  2023-05-07      4.0      410
7      900  2023-07-08      4.3      890
8     1500  2023-02-09      4.2      770
9    12000  2023-01-10      4.6      650
10    9000  2025-01-11      4.4      480
11    2000  2025-01-12      4.1      520
12     500  2025-01-13      4.0      430
13    3500  2025-01-14      4.3      610
14     700  2025-01-15      4.2      720
15    1800  2025-01-16      4.4      690
16    4500  2025-01-17      4.5      560
17    2200  2025-01-18      4.3      590
18    1200  2025-01-19      4.2      510
19     150  2025-01-20      4.1      450
20      20  2025-01-21      3.9      300
21     400  2025-01-22      4.0      340
22    1600  2025-01-23      4.2      390
23    1200  2025-01-24      4.3      580
24    2500  2025-01-25      4.4      640

,OrderID,CustomerID,products,categories,quantity,prices,order_dates,ratings,reviews
20,21,121,Pen,Stationery,100,20,2025-01-21,3.9,300
21,22,122,Coffee Mug,Kitchenware,24,400,2025-01-22,4.0,340
22,23,123,Desk Lamp,Home Decor,14,1600,2025-01-23,4.2,390
23,24,124,Charger,Electronics,30,1200,2025-01-24,4.3,580
24,25,125,Earbuds,Electronics,26,2500,2025-01-25,4.4,640

In [5]:
df.head(10)

,OrderID,CustomerID,products,categories,quantity,prices,order_dates,ratings,reviews
0,1,101,Smartphone,Electronics,10,15000,2025-01-01,4.5,1200
1,2,102,Laptop,Electronics,5,55000,2025-01-02,4.7,980
2,3,103,Headphones,Electronics,20,2500,2025-01-03,4.3,750
3,4,104,Smartwatch,Electronics,8,7000,2025-01-04,4.4,620
4,5,105,Bluetooth Speaker,Electronics,15,3000,2025-01-05,4.2,540
5,6,106,Power Bank,Electronics,25,1800,2025-01-06,4.1,680
6,7,107,USB Flash Drive,Electronics,30,800,2025-01-07,4.0,410
7,8,108,Wireless Mouse,Computer Accessories,40,900,2025-01-08,4.3,890
8,9,109,Keyboard,Computer Accessories,35,1500,2025-01-09,4.2,770
9,10,110,Monitor,Computer Accessories,6,12000,2025-01-10,4.6,650

In [30]:
# Q2: Use info() and describe() to get a comprehensive overview of the dataset
# Identify data types, missing values, and statistical summary
# Print the column names using columns attribute and shape of the dataset

df.info()
print(df.describe())
print(df.columns)
print("Shape of dataframe :", df.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   OrderID      25 non-null     int64
 1   CustomerID   25 non-null     int64
 2   products     25 non-null     object
 3   categories   25 non-null     object
 4   quantity     25 non-null     int64
 5   prices       25 non-null     int64
 6   order_dates  25 non-null     object
 7   ratings      25 non-null     float64
 8   reviews      25 non-null     int64
dtypes: float64(1), int64(5), object(3)
memory usage: 1.9+ KB
         OrderID  CustomerID    quantity       prices    ratings      reviews
count  25.000000   25.000000   25.000000     25.00000  25.000000    25.000000
mean   13.000000  113.000000   26.520000   5230.80000   4.264000   612.000000
std     7.359801    7.359801   20.914748  11029.03589   0.197653   203.469899
min     1.000000  101.000000    4.000000     20.00000   3.900000   300.000000
25%     7.000000  107.000000   14.000000    900.00000   4.100000   480.000000
50%    13.000000  113.000000   22.000000   1800.00000   4.300000   590.000000
75%    19.000000  119.000000   30.000000   3500.00000   4.400000   690.000000
max    25.000000  125.000000  100.000000  55000.00000   4.700000  1200.000000
Index(['OrderID', 'CustomerID', 'products', 'categories', 'quantity', 'prices',
       'order_dates', 'ratings', 'reviews'],
      dtype='object')
Shape of dataframe : (25, 9)

In [49]:
# Q3: Introduce 10% missing values randomly in Rating and Review columns
# Detect missing values and display the count of missing values per column
# Fill missing ratings with the median rating and missing reviews with "No review provided"
import numpy as np

np.random.seed(56)

rating_mask = np.random.rand(len(df))<0.1
df.loc[rating_mask,'ratings']=np.nan

review_mask = np.random.rand(len(df))<0.1
df.loc[review_mask,'reviews']=np.nan

print(df.isnull().sum())

median_rating = df['ratings'].median()
df.fillna(median_rating,inplace=True)
reviews = df.fillna("No review Provided",inplace=True)
print(df)

OrderID        0
CustomerID     0
products       0
categories     0
quantity       0
prices         0
order_dates    0
ratings        4
reviews        1
TotalAmount    0
dtype: int64
    OrderID  CustomerID           products            categories  quantity  \
0         1         101         Smartphone           Electronics        10
1         2         102             Laptop           Electronics         5
2         3         103         Headphones           Electronics        20
3         4         104         Smartwatch           Electronics         8
4         5         105  Bluetooth Speaker           Electronics        15
5         6         106         Power Bank           Electronics        25
6         7         107    USB Flash Drive           Electronics        30
7         8         108     Wireless Mouse  Computer Accessories        40
8         9         109           Keyboard  Computer Accessories        35
9        10         110            Monitor  Computer Accessories         6
10       11         111            Printer      Office Equipment         4
11       12         112           Backpack   Fashion Accessories        18
12       13         113       Water Bottle      Daily Essentials        50
13       14         114              Shoes              Footwear        22
14       15         115            T-Shirt              Clothing        45
15       16         116              Jeans              Clothing        28
16       17         117        Wrist Watch   Fashion Accessories        12
17       18         118         Sunglasses   Fashion Accessories        16
18       19         119             Wallet   Fashion Accessories        20
19       20         120           Notebook            Stationery        60
20       21         121                Pen            Stationery       100
21       22         122         Coffee Mug           Kitchenware        24
22       23         123          Desk Lamp            Home Decor        14
23       24         124            Charger           Electronics        30
24       25         125            Earbuds           Electronics        26

    prices order_dates  ratings  reviews  TotalAmount
0    15000  2023-07-01      4.5   1200.0       150000
1    55000  2023-05-02      4.7    980.0       275000
2     2500  2023-03-03      4.3    750.0        50000
3     7000  2023-01-04      4.4    620.0        56000
4     3000  2023-06-05      4.2    540.0        45000
5     1800  2023-01-06      4.1    680.0        45000
6      800  2023-05-07      4.0    410.0        24000
7      900  2023-07-08      4.3    890.0        36000
8     1500  2023-02-09      4.2    770.0        52500
9    12000  2023-01-10      4.6    650.0        72000
10    9000  2025-01-11      4.4    480.0        36000
11    2000  2025-01-12      4.3    520.0        36000
12     500  2025-01-13      4.0    430.0        25000
13    3500  2025-01-14      4.3    610.0        77000
14     700  2025-01-15      4.2    720.0        31500
15    1800  2025-01-16      4.4    690.0        50400
16    4500  2025-01-17      4.5    560.0        54000
17    2200  2025-01-18      4.3    590.0        35200
18    1200  2025-01-19      4.2    510.0        24000
19     150  2025-01-20      4.1    450.0         9000
20      20  2025-01-21      3.9    300.0         2000
21     400  2025-01-22      4.0    340.0         9600
22    1600  2025-01-23      4.3    390.0        22400
23    1200  2025-01-24      4.3      4.3        36000
24    2500  2025-01-25      4.4    640.0        65000

C:\Users\Prajwal barsagade\AppData\Local\Temp\ipykernel_18832\2101736619.py:17: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.fillna(median_rating,inplace=True)

In [50]:
# Q4: Create a new column 'TotalAmount' by multiplying Quantity and Price
# Add another column 'DiscountedPrice' that applies 10% discount on orders above $100
# Use conditional selection to filter orders where TotalAmount > $150

df['TotalAmount'] = df['quantity']*df['prices']

filtered_order = df[df['TotalAmount']>12000]
print(filtered_order)

    OrderID  CustomerID           products            categories  quantity  \
0         1         101         Smartphone           Electronics        10
1         2         102             Laptop           Electronics         5
2         3         103         Headphones           Electronics        20
3         4         104         Smartwatch           Electronics         8
4         5         105  Bluetooth Speaker           Electronics        15
5         6         106         Power Bank           Electronics        25
6         7         107    USB Flash Drive           Electronics        30
7         8         108     Wireless Mouse  Computer Accessories        40
8         9         109           Keyboard  Computer Accessories        35
9        10         110            Monitor  Computer Accessories         6
10       11         111            Printer      Office Equipment         4
11       12         112           Backpack   Fashion Accessories        18
12       13         113       Water Bottle      Daily Essentials        50
13       14         114              Shoes              Footwear        22
14       15         115            T-Shirt              Clothing        45
15       16         116              Jeans              Clothing        28
16       17         117        Wrist Watch   Fashion Accessories        12
17       18         118         Sunglasses   Fashion Accessories        16
18       19         119             Wallet   Fashion Accessories        20
22       23         123          Desk Lamp            Home Decor        14
23       24         124            Charger           Electronics        30
24       25         125            Earbuds           Electronics        26

    prices order_dates  ratings  reviews  TotalAmount
0    15000  2023-07-01      4.5   1200.0       150000
1    55000  2023-05-02      4.7    980.0       275000
2     2500  2023-03-03      4.3    750.0        50000
3     7000  2023-01-04      4.4    620.0        56000
4     3000  2023-06-05      4.2    540.0        45000
5     1800  2023-01-06      4.1    680.0        45000
6      800  2023-05-07      4.0    410.0        24000
7      900  2023-07-08      4.3    890.0        36000
8     1500  2023-02-09      4.2    770.0        52500
9    12000  2023-01-10      4.6    650.0        72000
10    9000  2025-01-11      4.4    480.0        36000
11    2000  2025-01-12      4.3    520.0        36000
12     500  2025-01-13      4.0    430.0        25000
13    3500  2025-01-14      4.3    610.0        77000
14     700  2025-01-15      4.2    720.0        31500
15    1800  2025-01-16      4.4    690.0        50400
16    4500  2025-01-17      4.5    560.0        54000
17    2200  2025-01-18      4.3    590.0        35200
18    1200  2025-01-19      4.2    510.0        24000
22    1600  2025-01-23      4.3    390.0        22400
23    1200  2025-01-24      4.3      4.3        36000
24    2500  2025-01-25      4.4    640.0        65000

In [69]:
# Q5: Select only the columns: Product, Category, TotalAmount, and Rating
# Filter and display all orders from the 'Electronics' category with Rating >= 4
electronics = df.loc[
    (df['categories'] == 'Electronics') & (df['ratings'] >= 4),
    ['products', 'categories', 'TotalAmount', 'ratings']
]

print(electronics)

             products   categories  TotalAmount  ratings
0          Smartphone  Electronics       150000      4.5
1              Laptop  Electronics       275000      4.7
2          Headphones  Electronics        50000      4.3
3          Smartwatch  Electronics        56000      4.4
4   Bluetooth Speaker  Electronics        45000      4.2
5          Power Bank  Electronics        45000      4.1
6     USB Flash Drive  Electronics        24000      4.0
23            Charger  Electronics        36000      4.3
24            Earbuds  Electronics        65000      4.4

In [67]:
# Q6: Use boolean indexing to find all orders where:
# - Quantity > 2 AND Price < 50 OR Rating == 5
# Display the count of such orders

filtered_orders = df[
    ((df['quantity'] > 2) & (df['prices'] < 50)) | (df['ratings'] == 5)
]

print("Number of matching orders:", filtered_orders.shape[0])

Number of matching orders: 1

In [68]:
# Q7: Sort the entire DataFrame by OrderDate (descending) and then by TotalAmount (descending)
# Create a new column 'SalesRank' that ranks products by TotalAmount in descending order

rankod=df.sort_values(by=['order_dates','TotalAmount'],ascending=[False,False])

(rankod['SalesRank'])=rankod['TotalAmount'].rank(ascending=False)
print(rankod[['products', 'TotalAmount', 'SalesRank']].head())

      products  TotalAmount  SalesRank
24     Earbuds        65000        5.0
23     Charger        36000       14.5
22   Desk Lamp        22400       22.0
21  Coffee Mug         9600       23.0
20         Pen         2000       25.0

In [70]:

# Q8: Find the top 5 best-selling products based on total quantity sold
# Display the product name and total quantity in descending order

top_5_products = (
    df.groupby('products')['quantity']
      .sum()
      .sort_values(ascending=False)
      .head(5)
)

print(top_5_products)

products
Pen               100
Notebook           60
Water Bottle       50
T-Shirt            45
Wireless Mouse     40
Name: quantity, dtype: int64

In [ ]:
# Q9: Group the data by 'Category' and calculate:
# - Total sales (sum of TotalAmount)
# - Average rating
# - Number of orders
# Display the results sorted by total sales

category_summary = (
    df.groupby('categories')
      .agg(
          TotalSales=('TotalAmount', 'sum'),
          AverageRating=('ratings', 'mean'),
          NumberOfOrders=('OrderID', 'count')
      )
      .sort_values(by='TotalSales', ascending=False)
)

print(category_summary)

                      TotalSales  AverageRating  NumberOfOrders
categories
Electronics               746000       4.322222               9
Computer Accessories      160500       4.366667               3
Fashion Accessories       149200       4.325000               4
Clothing                   81900       4.300000               2
Footwear                   77000       4.300000               1
Office Equipment           36000       4.400000               1
Daily Essentials           25000       4.000000               1
Home Decor                 22400       4.300000               1
Stationery                 11000       4.000000               2
Kitchenware                 9600       4.000000               1

In [77]:

# Q10: Create a pivot table showing average Price for each Category and Rating combination
# Use groupby with multiple columns (Category, Product) and aggregate multiple functions


pivot_table = df.pivot_table(
    values='prices',
    index='categories',
    columns='ratings',
    aggfunc='mean'
)

print(pivot_table)

grouped = df.groupby(['categories', 'products']).agg(
    AvgPrice=('prices', 'mean'),
    TotalSales=('TotalAmount', 'sum'),
    AvgRating=('ratings', 'mean'),
    OrderCount=('products', 'count')
).reset_index()

print(grouped)

ratings                3.9    4.0     4.1     4.2     4.3     4.4      4.5  \
categories
Clothing               NaN    NaN     NaN   700.0     NaN  1800.0      NaN
Computer Accessories   NaN    NaN     NaN  1500.0   900.0     NaN      NaN
Daily Essentials       NaN  500.0     NaN     NaN     NaN     NaN      NaN
Electronics            NaN  800.0  1800.0  3000.0  1850.0  4750.0  15000.0
Fashion Accessories    NaN    NaN     NaN  1200.0  2100.0     NaN   4500.0
Footwear               NaN    NaN     NaN     NaN  3500.0     NaN      NaN
Home Decor             NaN    NaN     NaN     NaN  1600.0     NaN      NaN
Kitchenware            NaN  400.0     NaN     NaN     NaN     NaN      NaN
Office Equipment       NaN    NaN     NaN     NaN     NaN  9000.0      NaN
Stationery            20.0    NaN   150.0     NaN     NaN     NaN      NaN

ratings                   4.6      4.7
categories
Clothing                  NaN      NaN
Computer Accessories  12000.0      NaN
Daily Essentials          NaN      NaN
Electronics               NaN  55000.0
Fashion Accessories       NaN      NaN
Footwear                  NaN      NaN
Home Decor                NaN      NaN
Kitchenware               NaN      NaN
Office Equipment          NaN      NaN
Stationery                NaN      NaN
              categories           products  AvgPrice  TotalSales  AvgRating  \
0               Clothing              Jeans    1800.0       50400        4.4
1               Clothing            T-Shirt     700.0       31500        4.2
2   Computer Accessories           Keyboard    1500.0       52500        4.2
3   Computer Accessories            Monitor   12000.0       72000        4.6
4   Computer Accessories     Wireless Mouse     900.0       36000        4.3
5       Daily Essentials       Water Bottle     500.0       25000        4.0
6            Electronics  Bluetooth Speaker    3000.0       45000        4.2
7            Electronics            Charger    1200.0       36000        4.3
8            Electronics            Earbuds    2500.0       65000        4.4
9            Electronics         Headphones    2500.0       50000        4.3
10           Electronics             Laptop   55000.0      275000        4.7
11           Electronics         Power Bank    1800.0       45000        4.1
12           Electronics         Smartphone   15000.0      150000        4.5
13           Electronics         Smartwatch    7000.0       56000        4.4
14           Electronics    USB Flash Drive     800.0       24000        4.0
15   Fashion Accessories           Backpack    2000.0       36000        4.3
16   Fashion Accessories         Sunglasses    2200.0       35200        4.3
17   Fashion Accessories             Wallet    1200.0       24000        4.2
18   Fashion Accessories        Wrist Watch    4500.0       54000        4.5
19              Footwear              Shoes    3500.0       77000        4.3
20            Home Decor          Desk Lamp    1600.0       22400        4.3
21           Kitchenware         Coffee Mug     400.0        9600        4.0
22      Office Equipment            Printer    9000.0       36000        4.4
23            Stationery           Notebook     150.0        9000        4.1
24            Stationery                Pen      20.0        2000        3.9

    OrderCount
0            1
1            1
2            1
3            1
4            1
5            1
6            1
7            1
8            1
9            1
10           1
11           1
12           1
13           1
14           1
15           1
16           1
17           1
18           1
19           1
20           1
21           1
22           1
23           1
24           1

In [ ]:
# Q11: Convert the Quantity and Price columns to NumPy arrays
# Create a 2D array combining these two columns
# Display array properties: shape, dtype, ndim, size
import numpy as np

qty_array = df['quantity'].to_numpy()
price_array = df['prices'].to_numpy()

combined_array = np.column_stack((qty_array, price_array))


print("Combined Array:")
print(combined_array)

print("\nArray Properties:")
print("Shape:", combined_array.shape)
print("Data Type:", combined_array.dtype)
print("Number of Dimensions:", combined_array.ndim)
print("Size:", combined_array.size)

Combined Array:
[[   10 15000]
 [    5 55000]
 [   20  2500]
 [    8  7000]
 [   15  3000]
 [   25  1800]
 [   30   800]
 [   40   900]
 [   35  1500]
 [    6 12000]
 [    4  9000]
 [   18  2000]
 [   50   500]
 [   22  3500]
 [   45   700]
 [   28  1800]
 [   12  4500]
 [   16  2200]
 [   20  1200]
 [   60   150]
 [  100    20]
 [   24   400]
 [   14  1600]
 [   30  1200]
 [   26  2500]]

Array Properties:
Shape: (25, 2)
Data Type: int64
Number of Dimensions: 2
Size: 50

In [78]:
# Q12: Create a 1D NumPy array of 100 random prices between 10 and 500
# Calculate mean, median, standard deviation, min, and max using NumPy functions
# Reshape this array into a 10x10 matrix

prices = np.random.uniform(10,500,100)

mean = np.mean(prices)
median = np.median(prices)
std = np.std(prices)
min = np.min(prices)
max = np.max(prices)


print("mean :",mean)
print("max  :",max)
print("min  :",min)
print("median :",median)
print("std :",std)



prices_matrix = prices.reshape(10, 10)

print("\n10x10 Matrix:\n", prices_matrix)

mean : 264.1179371569742
max  : 498.09376737412003
min  : 10.804793764914608
median : 270.86754331449026
std : 144.98705509813533

10x10 Matrix:
 [[484.05679954 148.33374982 414.88733864 192.35685842 239.80091064
  102.31035439  84.84043012  10.80479376 234.72419279  29.01835441]
 [369.33011126 342.85890261  81.58580015 272.28392801 481.46475446
  371.51909523 468.91896588 170.42283743 425.86597661 437.90297987]
 [ 83.85983705  18.53267714 223.05812368 207.57664166 173.56506566
   27.47481441 118.79772179 188.54104163 268.54945799 379.39028831]
 [349.11654502  64.00126694 494.51192808 469.71822008 255.2744149
  344.58538349 248.84177679 119.33386651 205.30531259 259.50322365]
 [483.56299314 111.32549087 262.64792189 290.415255   444.73263626
  348.2914701  226.54693313 364.63908013  40.01698824  26.17121044]
 [ 42.33134984 489.96755238 448.64583384 350.71058479  58.79607179
  399.53391307 331.92302928 146.76354641  50.67669687 256.45373641]
 [131.65834825 295.73212731 287.11861263 306.13895845 355.80542444
  354.72896921 134.20462215 491.10432705 167.04241751 308.86878448]
 [ 91.37739021 159.95414465 321.90496418 102.14105825 438.31598731
   46.7891216  313.33828279 350.68889415 390.21603701 326.0401721 ]
 [269.45115862 498.09376737 467.71367142 155.6057054   69.04444344
   84.27199367 329.78582673 344.21748184 495.61726065 451.88566274]
 [ 55.61251187 451.72664545 436.91286254 199.75487469 301.08318256
  440.87516927 277.3078738  342.68618708 178.05456769 151.94718986]]